<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/Clase15feb2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ciclo **While**

In [ ]:
i=0
while i<10:
  print(i)
  i=i+1

print("Ya salí del ciclo WHILE")

0
1
2
3
4
5
6
7
8
9
Ya salí del ciclo WHILE


Sentencia **ELSE**

In [ ]:
i=0
while i<10:
  print(i)
  i=i+1
else:
  print("Ya salí del ciclo WHILE y estoy dentro del ELSE")

0
1
2
3
4
5
6
7
8
9
Ya salí del ciclo WHILE y estoy dentro del ELSE


Sentencia **BREAK**

In [ ]:
i = 1
while i < 6:
  if i == 3:
    break
  print(i)
  i += 1

1
2


Sentencia **BREAK** es más fuerte que el **ELSE**

In [ ]:
i = 1
while i < 6:
  if i == 3:
    break
  print(i)
  i += 1
else:
  print("Me saco del ciclo WHILE")

1
2


Sentencia **CONTINUE**

In [ ]:
i = 1
while i < 6:
  if i == 3:
    continue
  print(i)
  i += 1

1
2


KeyboardInterrupt: 

En esta ocasión, se crea un bucle infinito debido a que al utilizar la sentencia **continue** nunca se hace la instrucción i=i+1, y por lo tanto i siempre tiene el valor i=3

ARREGLANDO EL BUCLE INFINITO

In [ ]:
i = 1
while i < 6:
  if i == 3:
    i += 1
    continue
  else:
    print("E")
  print(i)
  i += 1

E
1
E
2
E
4
E
5


Biblioteca **numpy**

In [15]:
import numpy as np

In [16]:
np.sqrt(4)

2.0

In [17]:
np.abs(-4)

4

In [20]:
np.round(np.cos(np.pi/2))

0.0

In [21]:
np.round(1.7989954941,6)

1.798995

**ARREGLOS 1D**

In [28]:
x=[1,2,3,4]
2*x
#me repite dos veces la lista

[1, 2, 3, 4, 1, 2, 3, 4]

In [30]:
x=np.array(x)
2*x
# me hace la multiplicación entrada a entrada

array([2, 4, 6, 8])

**Operador** +

In [31]:
y=[1,2,3,4]
y+y

[1, 2, 3, 4, 1, 2, 3, 4]

In [32]:
y=np.array(y)
y+y

array([2, 4, 6, 8])

Manera usual de declarar un arreglo

In [33]:
a=np.array([1,2,4,3])
a

array([1, 2, 4, 3])

**Matrices en numpy**

In [36]:
A=np.array([ [1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])