<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/Clase27feb24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
A=np.array([[1,1,1],[1,1,1],[1,1,1]])
B=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [ ]:
def MatMult(A,B):
  n=len(A)# cantidad de renglones de A
  C=np.zeros_like(A)
  for i in range(n):
    for j in range(n):
      for k in range(n):
        C[i][j]+=A[i][k]*B[k][j]

  return C

In [ ]:
MatMult(A,B)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
def SolveSystemMatDiag(A,b):
  x=np.zeros_like(b)
  n=len(b)
  for i in range(n):
    x[i]=b[i]/A[i][i]
  return x

In [ ]:
A=5*np.eye(10,10)
b=np.ones(10)
SolveSystemMatDiag(A,b)

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2])

$$x_{i}=(b_{i}-\sum_{j=0}^{i-1}A_{ij}x_{j})/A_{ii}$$

In [7]:
def SustDelante(A,b):
  x=np.zeros_like(b)
  n=len(A)
  for i in range(n):
    sum=0.0
    for j in range(i):
      # sumando desde j=0 hasta i-1 de Aij*xj
      sum+= A[i][j]*x[j]
    #bi- sumando dividido por Aii
    x[i]=(b[i]-sum)/A[i][i]

  return x

In [8]:
A=np.array([[1.0,0.0,0.0,0.0],[1.0,1.0,0.0,0.0],[1.0,1.0,1.0,0.0],[1.0,1.0,1.0,1.0]])
A

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [9]:
b=np.ones(4)

In [10]:
SustDelante(A,b)

array([1., 0., 0., 0.])

In [12]:
np.linalg.solve(A,b) # paqueteria de Python

array([1., 0., 0., 0.])

$$x_{i}=\frac{b_{i}-\sum_{j=i+1}^{n-1}A_{ij}x_{j}}{A_{ii}}$$

donde $i=n-1,...,0$

In [16]:
def SustAtras(A,b):
  x=np.zeros_like(b)
  n=len(A)

  for i in range(n-1,0,-1):
    sum=0.0
    for j in range(i+1,n):
      sum+=A[i][j]*x[j]
    x[i]=(b[i]-sum)/A[i][i]
  return x

In [17]:
A=np.array([[1.0,1.0,1.0,1.0],[0.0,1.0,1.0,1.0],[0.0,0.0,1.0,1.0],[0.0,0.0,0.0,1.0]])
A

array([[1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [18]:
b=np.ones(4)

In [20]:
SustAtras(A,b)

array([0., 0., 0., 1.])

In [19]:
np.linalg.solve(A,b) # paqueteria de Python

array([0., 0., 0., 1.])