<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/Clase16Abril24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[-1.,-1.,1.],[1.,3.,3.],[-1.,-1.,5.],[1.,3.,7.]])
A

array([[-1., -1.,  1.],
       [ 1.,  3.,  3.],
       [-1., -1.,  5.],
       [ 1.,  3.,  7.]])

In [3]:
Q=np.zeros_like(A)
R=np.zeros((A.shape[1],A.shape[1]))

Primer iteracion

In [4]:
Vi=A[:,0]
R[0,0]=np.linalg.norm(Vi)
Q[:,0]=Vi/R[0,0]

Segunda iteracion

In [5]:
R[0,1]=np.dot(Q[:,0].T,A[:,1])
Q[:,1]=A[:,1]-R[0,1]*Q[:,0]
R[1,1]=np.linalg.norm(Q[:,1])
Q[:,1]=Q[:,1]/R[1,1]

In [6]:
R

array([[2., 4., 0.],
       [0., 2., 0.],
       [0., 0., 0.]])

In [7]:
Q

array([[-0.5,  0.5,  0. ],
       [ 0.5,  0.5,  0. ],
       [-0.5,  0.5,  0. ],
       [ 0.5,  0.5,  0. ]])

Tercera iteracion

In [8]:
R[0,2]=np.dot(Q[:,0].T,A[:,2])
R[1,2]=np.dot(Q[:,1].T,A[:,2])
Q[:,2]=A[:,2]-R[0,2]*Q[:,0]-R[1,2]*Q[:,1]
R[2,2]=np.linalg.norm(Q[:,2])
Q[:,2]=Q[:,2]/R[2,2]

In [9]:
Q

array([[-0.5,  0.5, -0.5],
       [ 0.5,  0.5, -0.5],
       [-0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5]])

In [10]:
R

array([[2., 4., 2.],
       [0., 2., 8.],
       [0., 0., 4.]])