<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/clase23Abril.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A=np.array([[-1.,-1.,1.],[1.,3.,3.],[-1.,-1.,5.]])
A

array([[-1., -1.,  1.],
       [ 1.,  3.,  3.],
       [-1., -1.,  5.]])

In [22]:
R=np.copy(A)
ei=np.zeros(A.shape[0])
ei[0]=1.

x0=A[:,0]
norm_x0=LA.norm(x0)

u0=x0+np.sign(A[0,0])*norm_x0*ei
v0=u0/LA.norm(u0)

v0_c=np.reshape(v0,(-1,1))
v_vt=v0_c@v0_c.T
H0=np.eye(len(v0))-2.*v_vt
Q0=H0@R
Q0

array([[ 1.73205081,  2.88675135, -1.73205081],
       [ 0.        ,  1.57735027,  4.        ],
       [ 0.        ,  0.42264973,  4.        ]])

In [31]:
R=np.copy(Q0)
ei=np.zeros(Q0.shape[0])
ei[1]=1.

x0=np.zeros(Q0.shape[0])
x0[1:]=R[:,1:]
x0

array([[1.57735027, 4.        ],
       [0.42264973, 4.        ]])

In [ ]:
norm_x0=LA.norm(x0)

u0=x0+np.sign(A[0,0])*norm_x0*ei
v0=u0/LA.norm(u0)

v0_c=np.reshape(v0,(-1,1))
v_vt=v0_c@v0_c.T
H0=np.eye(len(v0))-2.*v_vt
Q0=H0@R
Q0