<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/Fact_Cholesky.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Se define la matriz A
A = np.array([[6.0,15.0,55.0],[15.0,55.0,225.0],[55.0,225.0,979.0]])

In [ ]:
import numpy as np

def Cholesky(A):
    """
    Realiza la descomposición de Cholesky de una matriz simétrica y definida positiva.

    La descomposición de Cholesky descompone una matriz \( A \) en el producto de una matriz triangular inferior \( L \) y su traspuesta: \( A = L \cdot L^T \).

    Parámetros:
    ----------
    A : numpy.ndarray
        Matriz cuadrada de tamaño \( n \times n \). Debe ser simétrica y definida positiva.

    Retorna:
    -------
    L : numpy.ndarray
        Matriz triangular inferior \( L \) de tamaño \( n \times n \) tal que \( A = L \cdot L^T \).

    Ejemplo:
    --------
    >>> A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
    >>> L = Cholesky(A)
    >>> print(L)
    [[ 2.  0.  0.]
     [ 6.  1.  0.]
     [-8.  5.  3.]]

    Notas:
    ------
    - La matriz \( A \) debe ser simétrica y definida positiva para que la descomposición
       de Cholesky sea válida.
    - Esta implementación no verifica si la matriz es simétrica o definida positiva.
    Es responsabilidad del usuario asegurarse de que los datos de entrada cumplan con estos requisitos.

    """

    n = A.shape[0]
    L = np.zeros_like(A)

    for k in range(n):
        for i in range(k + 1):
            if k == i:
                sum = 0.0
                for j in range(k):
                    sum += L[k][j] * L[k][j]
                L[k][k] = np.sqrt(A[k][k] - sum)

            else:
                sum = 0.0
                for j in range(i):
                    sum += L[i][j] * L[k][j]
                L[k][i] = (A[k][i] - sum) / L[i][i]

    return L


In [ ]:
#aplicamos la descomposicion de Cholesky
Cholesky(A)

array([[ 2.44948974,  0.        ,  0.        ],
       [ 6.12372436,  4.18330013,  0.        ],
       [22.45365598, 20.91650066,  6.11010093]])

Validando con Nympy

In [ ]:
L_num = np.linalg.cholesky(A)
# Se imprimen ambas matrices
print(L_num)