<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/Fact_QR_Givens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy import linalg as LA
from numba import jit

In [2]:
A=np.array([[6.0,5.0,0.0],[5.0,1.0,4.0],[0.0,4.0,3.0]])
A

array([[6., 5., 0.],
       [5., 1., 4.],
       [0., 4., 3.]])

In [3]:
def GivensMatrix(x,i,j):
    """ Compute the Givens rotations matrix
        Inputs:
              x: float array
              i: int number ( ith column,row)
              j: int number ( jth column,row)

        Outputs:
              float 2darray

        >>>  A=np.array([-1.0,2.0,3.0])
             GivensMatrix(A,0,1)
            [[-0.4472136   0.89442719  0.        ]
             [-0.89442719 -0.4472136   0.        ]
             [ 0.          0.          1.        ]]
    """
    vec=np.array([x[i], x[j]])
    rnorm=LA.norm(vec)
    c=vec[0]/rnorm;s=vec[1]/rnorm;
    Giv=np.eye(x.shape[0])
    Giv[i,i]=c; Giv[i,j]=s;
    Giv[j,j]=c;  Giv[j,i]=-s

    return Giv

In [4]:
class FactGivens:
    def __init__(self,A):
        self.A=A # original matrix
        self.rows=self.A.shape[0] # rows
        self.col=self.A.shape[1] # columns
        self.min=np.minimum(self.col,self.rows-1) # minimum between
        # columns and rows
        self.R=np.copy(self.A)

    def Givens(self):
        Qs=[]
        for COL in range(self.min):
            vi=self.R[:,COL]
            for ROW in range(COL+1,self.rows):
                if(vi[ROW]!=0):
                    GM=GivensMatrix(vi,ROW-1,ROW)
                    self.R=GM @ self.R
                    Qs.append(GM)
        self.Q=Qs[0].T
        for i in range(1,len(Qs)):
        	self.Q=self.Q@Qs[i].T

        return self.R,self.Q

In [7]:
Fac=FactGivens(A)
R,Q=Fac.Givens()

print(Q)

[[ 0.76822128  0.33265418  0.54697099]
 [ 0.6401844  -0.39918502 -0.65636519]
 [ 0.          0.854396   -0.51962244]]


In [8]:
print(R)

[[ 7.81024968e+00  4.48129080e+00  2.56073760e+00]
 [ 2.88448398e-16  4.68166987e+00  9.66447932e-01]
 [ 4.74285054e-16  0.00000000e+00 -4.18432806e+00]]


In [6]:

# Realizar la factorización QR
Q, R = np.linalg.qr(A)

print("Matriz Q:")
print(Q)

Matriz Q:
[[-0.76822128  0.33265418 -0.54697099]
 [-0.6401844  -0.39918502  0.65636519]
 [-0.          0.854396    0.51962244]]


In [9]:

print("\nMatriz R:")
print(R)


Matriz R:
[[ 7.81024968e+00  4.48129080e+00  2.56073760e+00]
 [ 2.88448398e-16  4.68166987e+00  9.66447932e-01]
 [ 4.74285054e-16  0.00000000e+00 -4.18432806e+00]]
