<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/Fact_QR_GrandSchmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def QR(A):
  Q=np.empty_like(A) ## matriz Q
  R=np.zeros([A.shape[1],A.shape[1]]) ## matriz cuadrada
  vi=np.zeros([A.shape[1]])

  for i in range(A.shape[1]):
    vi=A[:,i]
    for j in range(i):
      R[j,i]=np.dot(Q[:,j].T,vi)
      vi = vi - R[j,i]*Q[:,j]
      #vi = a2 - (q1T, a2)* q1
    R[i,i]=np.linalg.norm(vi,2)
    Q[:,i]=vi/R[i,i]

  return Q,R


In [ ]:
# matriz a que se quiere aplicar factorizacion QR
A = np.array([[-1.0,-1.0,1.0],[1.0,3.0,3.0],[-1.0,-1.0,5.0],[1.0,3.0,7.0]])
A

array([[-1., -1.,  1.],
       [ 1.,  3.,  3.],
       [-1., -1.,  5.],
       [ 1.,  3.,  7.]])

In [ ]:
Q,R=QR(A)
# mostrar ambas matrices
print(Q)
print(R)

# comprobacion
print(np.matmul(Q,R))

[[-0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5]
 [-0.5  0.5  0.5]
 [ 0.5  0.5  0.5]]
[[2. 4. 2.]
 [0. 2. 8.]
 [0. 0. 4.]]
[[-1. -1.  1.]
 [ 1.  3.  3.]
 [-1. -1.  5.]
 [ 1.  3.  7.]]


In [ ]:
# funcion de numpy encargada de la factorizacion QR
Q1,R1 = np.linalg.qr(A)

# mostrar ambas matrices
print(Q1)
print(R1)

# comprobacion
print(np.matmul(Q1,R1))

[[-0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5]]
[[ 2.  4.  2.]
 [ 0. -2. -8.]
 [ 0.  0. -4.]]
[[-1. -1.  1.]
 [ 1.  3.  3.]
 [-1. -1.  5.]
 [ 1.  3.  7.]]
