<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/Fact_QR_HouseHolder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
from numpy import linalg as LA

In [13]:
A=np.array([[-1.,-1.,1.],[1.,3.,3.],[-1.,-1.,5.]])
A

array([[-1., -1.,  1.],
       [ 1.,  3.,  3.],
       [-1., -1.,  5.]])

In [14]:
def Hfix(Haux,OM):
  """
    Compute the HouseHolder matrix
        Inputs:
              Huax: float 2darray
              OM (Original Matrix): float 2darray
        Outputs:
              float 2darray

        >>>  OM=np.array([[0,1,1],[1,2,3],[1,1,1]])
            Haux=[[-0.16910198 -0.98559856]
            [-0.98559856  0.16910198]]
             Hfix(Haux,OM)
             >>>[[ 1.          0.          0.        ]
             [ 0.         -0.16910198 -0.98559856]
             [ 0.         -0.98559856  0.16910198]]
  """
  if Haux.shape==OM.shape:
    return Haux
  else:
    i=OM.shape[0]-Haux.shape[0]
    H=np.eye(OM.shape[0])
    for j in range(Haux.shape[0]):
      fil=j+i
      for k in range(Haux.shape[0]):
          col=k+i
          H[fil][col]=Haux[j][k]

    return H

In [15]:
def HouseHolder(A):
    Qs=[]
    R=np.copy(A)
    for i in range(R.shape[0]-1):
        ai=R[:,i][i:]
        ei=np.eye(ai.shape[0])[0]
        u=ai+np.sign(ai[0])*LA.norm(ai)*ei
        beta=1/(u.T@u)
        uu=u.reshape((ai.shape[0],1))
        uuT=u.reshape((1,ai.shape[0]))
        Haux=np.eye(ai.shape[0])-2*beta*(uu@uuT)
        H=Hfix(Haux,A)
        R=H @ R
        Qs.append(H)

    Q=Qs[0]
    for i in range(1,len(Qs)):
        Q=Q@Qs[i]

    return Q,R

In [16]:
Q,R=HouseHolder(A)

In [17]:
Q

array([[-5.77350269e-01, -4.08248290e-01, -7.07106781e-01],
       [ 5.77350269e-01, -8.16496581e-01, -1.13379573e-16],
       [-5.77350269e-01, -4.08248290e-01,  7.07106781e-01]])

In [18]:
R

array([[ 1.73205081e+00,  2.88675135e+00, -1.73205081e+00],
       [ 7.85046229e-17, -1.63299316e+00, -4.89897949e+00],
       [ 1.35973996e-16,  4.32306238e-17,  2.82842712e+00]])

In [19]:
# Realizar la factorización QR
Q, R = np.linalg.qr(A)

print("Matriz Q:")
print(Q)

Matriz Q:
[[-0.57735027 -0.40824829 -0.70710678]
 [ 0.57735027 -0.81649658  0.        ]
 [-0.57735027 -0.40824829  0.70710678]]


In [20]:
print("\nMatriz R:")
print(R)


Matriz R:
[[ 1.73205081  2.88675135 -1.73205081]
 [ 0.         -1.63299316 -4.89897949]
 [ 0.          0.          2.82842712]]
