<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/LU_19mar24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2,3],[2,3,1],[-2,3,-2]])
A

array([[ 1,  2,  3],
       [ 2,  3,  1],
       [-2,  3, -2]])

In [3]:
L=np.eye(A.shape[0])
L1=np.eye(A.shape[0])
U=np.copy(A)
L,U

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1,  2,  3],
        [ 2,  3,  1],
        [-2,  3, -2]]))

Primera iteracion

In [4]:
# no puedo empezar desde el indice 0
#porque el indice 0 es el número 1 de la matriz L
# que corresponde a cuando le sumas la matriz identidad
for i in range(1,A.shape[0]):
  L[i,0]=-U[i,0]/U[0,0]
L1=L1*L
L

array([[ 1.,  0.,  0.],
       [-2.,  1.,  0.],
       [ 2.,  0.,  1.]])

In [5]:
U=L@U
U

array([[ 1.,  2.,  3.],
       [ 0., -1., -5.],
       [ 0.,  7.,  4.]])

In [6]:
L=np.eye(A.shape[0])
for i in range(2,A.shape[0]):
  L[i,1]=-U[i,1]/U[1,1]
L1=L1*L
L

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 7., 1.]])

In [7]:
U=L@U
U

array([[  1.,   2.,   3.],
       [  0.,  -1.,  -5.],
       [  0.,   0., -31.]])

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])