<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/LU_PivotParcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[0,1,1],[-1,2,-4],[2,-5,1]])
A

array([[ 0,  1,  1],
       [-1,  2, -4],
       [ 2, -5,  1]])

Observacion 1

In [3]:
B=np.copy(A)
B[[0,2]]=B[[2,0]]
B

array([[ 2, -5,  1],
       [-1,  2, -4],
       [ 0,  1,  1]])

Observacion 2

In [4]:
B[:,0]

array([ 2, -1,  0])

In [5]:
np.argmax(np.abs(A[:,0]))

2

Primera iteracion

In [3]:
U=np.copy(A)
k=np.argmax(np.abs(U[:,0]))
U[[0,k]]=U[[k,0]]
L1=np.eye(A.shape[0])
L=np.eye(U.shape[0])
for i in range(1,A.shape[0]):
  L[i,0]=-U[i,0]/U[0,0]
U=L@U
L1=L1@L

In [4]:
U,L1

(array([[ 2. , -5. ,  1. ],
        [ 0. , -0.5, -3.5],
        [ 0. ,  1. ,  1. ]]),
 array([[1. , 0. , 0. ],
        [0.5, 1. , 0. ],
        [0. , 0. , 1. ]]))

Segunda iteracion

In [8]:
k=np.argmax(np.abs(U[1:,1]))
U[[1,k+1]]=U[[k+1,1]]
U

array([[ 2. , -5. ,  1. ],
       [ 0. ,  1. ,  1. ],
       [ 0. , -0.5, -3.5]])

In [11]:
L1=np.eye(U.shape[0])
L=np.eye(U.shape[0])
for i in range(1,A.shape[0]):
  L[i,0]=-U[i,0]/U[0,0]
U=L@U
L1=L1@L

In [10]:
U,L1

(array([[ 2. , -5. ,  1. ],
        [ 0. ,  1. ,  1. ],
        [ 0. , -0.5, -3.5]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))