<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/LU_PivoteoParcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[1.0,2.0,2.0],[4.0,4.0,2.0],[4.0,6.0,4.0]])
A

array([[1., 2., 2.],
       [4., 4., 2.],
       [4., 6., 4.]])

In [3]:
def LU_PartialPivot(A):
  U=np.copy(A)
  Ps=[]
  Ls=[]
  for j in range(U.shape[0]):
    P=np.eye(U.shape[0])
    L=np.eye(U.shape[0])
    k=np.argmax(np.abs(U[j:,j]))+j
    print(f"k={k}")
    U[[j,k]]=U[[k,j]]
    P[[j,k]]=P[[k,j]]
    for i in range(j+1,A.shape[0]):
      L[i,j]=-U[i,j]/U[j,j]
    U=L@U

    Ps.append(P)
    Ls.append(np.linalg.inv(L))

  PM=np.eye(U.shape[0])
  for i in range(len(Ps)-1,-1,-1):
    PM=(Ps[i]@Ls[i])@PM
  PM

  return PM,U

In [4]:
L,U=LU_PartialPivot(A)
L,U

k=1
k=2
k=2


(array([[0.25, 0.5 , 1.  ],
        [1.  , 0.  , 0.  ],
        [1.  , 1.  , 0.  ]]),
 array([[4. , 4. , 2. ],
        [0. , 2. , 2. ],
        [0. , 0. , 0.5]]))

In [5]:
L@U

array([[1., 2., 2.],
       [4., 4., 2.],
       [4., 6., 4.]])