<a href="https://colab.research.google.com/github/seismomat/Numerico2024_2/blob/main/LU_PivotParcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2,2],[4,4,2],[4,6,4]])
A

array([[1, 2, 2],
       [4, 4, 2],
       [4, 6, 4]])

Observacion 1

In [ ]:
B=np.copy(A)
B[[0,2]]=B[[2,0]]
B

array([[ 2, -5,  1],
       [-1,  2, -4],
       [ 0,  1,  1]])

Observacion 2

In [ ]:
B[:,0]

array([ 2, -1,  0])

In [ ]:
np.argmax(np.abs(A[:,0]))

2

Primera iteracion

In [3]:
U=np.copy(A)
Ls=[]
Ps=[]
k=np.argmax(np.abs(U[0:,0]))
print(f"k={k}")
L=np.eye(U.shape[0])
P=np.eye(U.shape[0])
U[[0,k]]=U[[k,0]]
P[[0,k]]=P[[k,0]]
for i in range(1,A.shape[0]):
  L[i,0]=-U[i,0]/U[0,0]
U=L@U
Ls.append(np.linalg.inv(L))
Ps.append(P)

k=1


In [4]:
U,L

(array([[4. , 4. , 2. ],
        [0. , 1. , 1.5],
        [0. , 2. , 2. ]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [-0.25,  1.  ,  0.  ],
        [-1.  ,  0.  ,  1.  ]]))

Segunda iteracion

In [5]:
k=np.argmax(np.abs(U[1:,1]))
print(f"k={k}")
P=np.eye(U.shape[0])
U[[1,k+1]]=U[[k+1,1]]
P[[1,k+1]]=P[[k+1,1]]
U

k=1


array([[4. , 4. , 2. ],
       [0. , 2. , 2. ],
       [0. , 1. , 1.5]])

In [6]:
L=np.eye(U.shape[0])
for i in range(2,A.shape[0]):
  L[i,1]=-U[i,1]/U[1,1]

L

array([[ 1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. , -0.5,  1. ]])

In [7]:
U=L@U
U

array([[4. , 4. , 2. ],
       [0. , 2. , 2. ],
       [0. , 0. , 0.5]])

In [8]:
Ls.append(np.linalg.inv(L))
Ps.append(P)

In [9]:
Ls

[array([[1.  , 0.  , 0.  ],
        [0.25, 1.  , 0.  ],
        [1.  , 0.  , 1.  ]]),
 array([[1. , 0. , 0. ],
        [0. , 1. , 0. ],
        [0. , 0.5, 1. ]])]

In [6]:
def LU_PartialPivot(A):
  U=np.copy(A)
  Ls=[]
  Ps=[]

  for j in range(U.shape[0]):
    k=np.argmax(np.abs(U[j:,j]))+j
    L=np.eye(U.shape[0])
    P=np.eye(U.shape[0])
    U[[j,k]]=U[[k,j]]
    P[[j,k]]=P[[k,j]]
    for i in range(j+1,U.shape[0]):
      L[i,j]=-U[i,j]/U[j,j]
    U=L@U
    Ls.append(np.linalg.inv(L))
    Ps.append(P)

  return U

In [7]:
Uu=LU_PartialPivot(A)

In [8]:
Uu

array([[4. , 4. , 2. ],
       [0. , 2. , 2. ],
       [0. , 0. , 0.5]])